name: Manually validate breakout session issue

on:
  workflow_dispatch:
    inputs:
      sessionNumber:
        description: 'Session issue number'
        required: true
        type: string

jobs:
  validate-session:
    name: Validate breakout session
    runs-on: ubuntu-latest
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout latest version of release script
        uses: actions/checkout@v3
        with:
          ref: main

      # Note: no "package-lock.json" and no "npm ci" on purpose to retrieve
      # latest version of w3c/tpac-breakouts tools (which are unversioned)
      - name: Install dependencies
        run: npm install

      - name: Validate session and update issue labels accordingly
        run: npx validate-session ${{ inputs.sessionNumber }}
        env:
          # URL of the annual TPAC XXXX breakout project.
          # The PROJECT_OWNER and PROJECT_NUMBER variables must be defined on
          # the repository. PROJECT_OWNER_TYPE needs to be set to "user" if
          # project belongs to a user. It may be omitted otherwise (or set to
          # 'org"').
          PROJECT_OWNER: ${{ vars.PROJECT_OWNER_TYPE || 'organization' }}/${{ vars.PROJECT_OWNER || 'w3c' }}
          PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}

          # Same valid Personal Access Token (classic version) as above, with
          # project and public_repo scope.
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}

          # Mapping between chair GitHub identities and W3C IDs must be stored
          # in a variable. Structure is a JSON object with identities as keys.
          CHAIR_W3CID: ${{ vars.CHAIR_W3CID }}

